### ISSUE TITLE
alias band.musician as band.owner for clarity

### ISSUE THREAD

**Issue by nathanallen** [LilyCole/bandapp#33]
See https://github.com/LilyCole/bandapp/blob/c030da5bdc9770c04caeef15d550c92c294a82ba/app/controllers/bands_controller.rb#L63

**Comment by Lily-Brown** [comment]
To Do: 
- In Band model --
  alias_method :owner, :musician

**Comment by Lily-Brown** [comment]
Fixes issue in Pull Request #40
