### ISSUE TITLE
What's the difference between deleting a band opening, and a band member?

### ISSUE THREAD

**Issue by nathanallen** [LilyCole/bandapp#36]
Currently they are the same:
* https://github.com/LilyCole/bandapp/blob/master/app/views/bands/show.html.erb#L52
* https://github.com/LilyCole/bandapp/blob/master/app/views/bands/show.html.erb#L64

But they seem like very different things to me.

**Comment by Lily-Brown** [comment]
@nathanallen -- It depends on what you mean by this.
Deleting both a band opening and a band member is essentially removing that record from the Join table. There are two different cases that would require you to do this, but both would involve deleting the associated row in the Join table.

1) Remove Band Member: This would happen when a Band's Owner removes a Musician from the Band, dissolving the relationship of Band/Musician/Instrument and removing this row from the Join table. 

2) Remove Band Opening: This would happen when a Band's Owner decides they aren't looking for an X-player and removes the Opening associated with the Band, removing this row (where band_id and instrument_id are populated but musician_id is empty) from the Join table.

Please let us know if this helps clarify or if you are thinking of a complete other workflow.

**Comment by nathanallen** [comment]
My assumption is that: removing a band member creates an opening.

**Comment by Lily-Brown** [comment]
@nathanallen We considered that for a while... With the workflow that removing a member, creates an opening where the Band/Instrument relationship still exists.. But decided that there could be a number of reasons for removing a member wouldn't necessarily maintain that relationship:
- Band doesn't want to replace Member that was removed
- Band decides they don't need that Instrument in their band any more

We had decided that if the Band wanted to replace the Member, they would create another Opening. Maybe a future Feature Request? :)
